### ISSUE TITLE
Timestamping data streams

### ISSUE THREAD

**Issue by charlie-dufort** [otosense/know#9]
See [this doc](https://analog.sharepoint.com/:w:/r/sites/CbM_OtoSense/Reusable/Shared%20Documents/Documents/Otosense/Components/Managing%20Time.docx?d=w7a1cffcb14cf4e308e7eeae10418aeaf&csf=1&web=1&e=g70Xcj) for details of Thor's original thoughts in 2018 and discussion between Thor and myself when the topic was revived a few days ago.

Also see [Why do we need timestamp precision](https://github.com/i2mint/creek/wiki/Why-do-we-need-timestamp-precision%3F) which is a nice synopsis of why we care and what properties to look out for. 

Start with those documents before reading further.

## Objective
Have a reliable way to timestamp data down to the sample level, with no drift relative to the host-system time, and no timestamp discontinuities.  

## Sample rate uncertainties
Edge devices come with a data acquisition module to acquire sound and vibration signals. The sample rate of these data acquisition modules have a certain level of accuracy.  

**Example of sample rate accuracy for the WebDAQ 504**: +/- 50 ppm, which means:
- sr = 51,200 Hz has an uncertainty of +/- 2.56 Hz
- sr = 25,600 Hz has an uncertainty  +/- 1.28 Hz
- And so on…

Seen differently, it’s a potential drift of (whatever the sample rate selected):
- 50 us / sec
- 3 ms / min
- 180 ms / hr
- 4.32 s / day

On a side note, the host-system clock also has its own level of accuracy and is subjected to drift relative to the coordinated universal time. Operating Systems address this issue by time-synch their clock with the coordinated universal time when they are connected to the Internet, using NTP or similar protocol.  
There can also be use cases where the host-system clock needs to be synchronized with another system, like a PLC for instance.  

In this issue, we assume the host-system time is the reference, and we want a reliable way to timestamp sound data with no drift from this reference.  

### Drift relative to host-system time 
**Example of a use case encountered in the field**  
Sound data buffers were timestamped by relying on the nominal sample rate with, for only absolute reference, the host-system time at the beginning of data acquisition, with no time-synch thereafter:  

`ts_buf_i = ts_0 + i*buf_sz / sr`, with:
- `ts_buf_i` timestamp of buffer `i`
- `ts_0` host-system time used to timestamp the first buffer generated after data acquisition was started
- `i` current buffer number 
- `buf_sz` buffer size, in number of samples
- `sr` nominal sample rate  

The sound data acquisition module was run continuously. Sessions were extracted based on receipt of events timestamped by the host-system time. To extract the data of interest, the timestamp of these events were compared to the timestamp of the incoming sound buffers which, as a reminder, were calculated by relying on the nominal sample rate, with no time synch with the host-system time after data acquisition was started.  

Because of the sample rate uncertainty described above, sound data timestamps and external event timestamps got misaligned after a certain moment, which means that sessions no longer contained the data of interest.  

After a few days, I noticed the time shift in the extracted sessions, so I asked VM to time sync regularly the data acquisition backend module with the host-system time. To do so, I think he timestamped with the system time each buffer coming from the DAQ module (there's 1 incoming buffer / sec), but I might be wrong. Anyway, the problem was solved afterwards.  

### Timestamp discontinuities
The example above showed us that, to avoid drift from the host-system time, it was necessary to regularly time-synch the timestamps of the incoming data stream with the host-system time. This can be done at every buffer, or on longer periods of time. Whatever the chosen interval, let's call it a "block".    

Now, how to infer timestamps at the sample level within a block? We could rely on the nominal sample rate, by first making sure blocks are short enough so that the sample rate uncertainty can be ignored.  

This can lead to the following discontinuities:  
- **Time gap:** the actual sample rate is lower than the nominal sample rate -> Blocks contain fewer samples than expected -> there is a time gap between the last sample of block *i* and the first sample of block *i+1* (i.e. the time interval between these two samples is bigger than the time interval between the other samples)  
- **Time overlap:** the actual sample rate is higher than the nominal sample rate -> Blocks contain more samples than expected -> there is a time overlap between the last sample of block *i* and the first sample of block *i+1* (i.e. the time interval between these two samples is negative!)      

## Proposed solution
Timestamp beginning and end of data blocks (respectively referred as *bt* and *tt*) with host-system time and, to infer the timestamp of the sample *m* within a block, use the following formula:  

`ts_m = bt + m/n * (tt - bt)`, with:  
- `m`: sample index (zero-based indexing)
- `n`: number of samples in the block of interest

One can also calculate a 'revised' sample rate for this block:  
`revised_sr = n / (tt - bt)`

**Comment by thorwhalen** [comment]
Regarding the (new/edited) proposed solution:


> Timestamp beginning and end of data blocks (respectively referred as *bt* and *tt*) with host-system time and, to infer sample timestamps within a block, use a "revised" sample rate calculated as follows:  
> 
> `revised_sr = nof_samples / (tt - bt)`, with `nof_samples` the number of samples in the block of interest.  
>  
> The timestamp of sample *i* can then be inferred as follows:
> 
> `ts_i = bt + i / revised_sr`, with `i` the sample zero_based index
> 

It's important to point out that all of these formulas have to do with the

```
sr = n_samples / duration_in_seconds = n_samples / (bt - tt)
```

formula, we'll use it to convert time to and from sample offsets; as we are already doing now. 

**The important difference here is that where we took the sample rate as a known quantity before, we now have to get an estimate of that sample rate first.**

I'd correct the proposal with a few addendums:

Remove the "Timestamp beginning and end of data blocks with host-system time", or rather state it as one way that "it" can be done. Because "it" is a separate concern. What is the concern(s) here? 

We want to 

(a) gather a collection of `(n_samples, duration)`

in order to

(b) estimate the sample rate

in order to

(c) have it to convert time from/to sample offsets (and a session time reference).

As far as I understand, your solution solves (a) by persisting blocks with an associated `bt` and `tt` and (b) through the `revised_sr = nof_samples / (tt - bt)` formula. 

But let's see what other options might be. I'll propose one for (a) and one for (b), but am not saying it's better than yours. I am saying that it's better than yours... in some contexts (and possibly in our current one). 


## Alternative to (a) (stats gathering)

Gather `(n_samples, bt, tt)` triples in the `stream2py` buffer. Note that if the buffer items are of constant (sample) length and the `tt_{i} == bt_{i+1}`, then we only really need the `bt` (and for the tt/bt thing, consider that getting the tt, and then the next bt might have a cost in possibly decreasing it's accuracy). 

If the buffer is big enough, we may gather enough information to be able to make a good estimate before we need to persist any signal, and we can continue things as usual (just using the correct sample rate). 


## Alternative to (b) (estimating the sample rate)

Critique: The `revised_sr = n_samples / (tt - bt)` seems to infer that 
* you're estimating the sample rate based on one observation only
* we're not taking into account the "declared" sample rate at all

Regarding the first, here's a question: What would lead to a better estimate: Basing it on 1 observation lasting approximately 10s, or basing it on 10 observations of 1s? (Genuine question). 

Regarding the second: **We should definitely include the theoretical sample rate in the estimate!**. It's valuable information! Not including it is assuming it could be **anything**, but we know it's not. There are know methods to do these kind of estimates. I favor Bayesian estimates, but won't get all religious of you about that. 

Here's what chatGPT gave me when I asked:


```python
import numpy as np
from scipy.stats import norm

def bayesian_speed_estimate(prior_speed_mean, prior_speed_standard_deviation, observed_distance, observed_duration):
    def likelihood(speed, observed_distance, observed_duration):
        return norm.pdf(observed_distance / speed, loc=observed_duration, scale=0.01)
    
    posterior_mean = (likelihood(prior_speed_mean, observed_distance, observed_duration) * prior_speed_mean +
                      observed_distance / observed_duration * prior_speed_standard_deviation ** 2) / \
                     (likelihood(prior_speed_mean, observed_distance, observed_duration) + 
                      prior_speed_standard_deviation ** 2 / observed_duration ** 2)
    
    posterior_standard_deviation = np.sqrt(
        (prior_speed_standard_deviation ** 2 * likelihood(prior_speed_mean, observed_distance, observed_duration)) /
        (likelihood(prior_speed_mean, observed_distance, observed_duration) +
         prior_speed_standard_deviation ** 2 / observed_duration ** 2))
    
    return posterior_mean, posterior_standard_deviation
```

In the above, I used descriptive argument names in my query, to make sure chatGPT would understand. But here would be (in my opinion) a more (globally) readable version with single characters:

```python
import numpy as np
from scipy.stats import norm


def bayesian_speed_estimate(μ, σ, d, t):
    def likelihood(speed, d, t):
        return norm.pdf(d / speed, loc=t, scale=0.01)

    new_μ = (likelihood(μ, d, t) * μ + d / t * σ**2) / (
        likelihood(μ, d, t) + σ**2 / t**2
    )

    new_σ = np.sqrt(
        (σ**2 * likelihood(μ, d, t)) / (likelihood(μ, d, t) + σ**2 / t**2)
    )

    return new_μ, new_σ

```

Note: This is a perfect example of how longer names make the code more readable, yes, but only "locally", when you're reading one or a few variable names and you want to know what they're referring to. But shorter names make the global "logic" of an expression or function more "readable".

**Comment by charlie-dufort** [comment]
I have edited the end of the issue to highlight the fact that the primary objective is to propose a method to infer the timestamp of a sample within a block of data itself timestamped with a *bt* and a *tt*, and not calculate a revised sample rate, even though the principle is equivalent to calculating a revised sample rate **only valid for the block of interest**.  

Note there is no 'revised_sr' in the new formula to infer the timestamp of a sample *m* within a block:  
`ts[m] = bt + m/n * (tt - bt)`, with:  
- `m`: sample index (zero-based indexing)
- `n`: number of samples in the block of interest  

"Timestamp beginning and end of data blocks with host-system time" is indeed not the objective but a condition for the method to thereafter infer timestamps at the sample level. However, this is not completely another concern since blocks will actually be timestamped using this same method, based on buffers that are themselves timestamped using the system time.  
So I agree that saying "Timestamp beginning and end of data blocks **with host-system time**" is not completely true. I should talk about buffers, not blocks, and then say blocks *bt* and *tt* will be calculated with the above formula using the buffers *bt* and *tt*.    
Might sound confusing explained like that, but everything is illustrated on [this Miro board](https://miro.com/app/board/uXjVPsuJtdM=/?share_link_id=265648244830). All the methods described on the Miro board have been discussed and collegially validated with Andie and Valentin.  
To answer your question, bts and tts are stored in the session or block metadata (in a database, then).  

Data will be acquired using the "fixed size block" method you described:  
>  we would set things up (thanks to the buffer) so that all blocks of a same session would have fixed size (except possibly the last block).  


The first part of your "Alternative to (a)" is exactly what's described in the Miro board.  
> Gather (n_samples, bt, tt) triples in the stream2py buffer. Note that if the buffer items are of constant (sample) length and the tt_{i} == bt_{i+1}, then we only really need the bt (and for the tt/bt thing, consider that getting the tt, and then the next bt might have a cost in possibly decreasing it's accuracy).  


The second part of your "Alternative to (a)" would imply that we are looking to estimate the "actual" sample rate of the DAQ terminal, and then use it to timestamp data like we have done up to now.  
> If the buffer is big enough, we may gather enough information to be able to make a good estimate before we need to persist any signal, and we can continue things as usual (just using the correct sample rate).  

Assumption confirmed by:  
> The important difference here is that where we took the sample rate as a known quantity before, we now have to get an estimate of that sample rate first.  

I'd tend to disagree with this approach, because nothing tells us the actual sample rate does not vary over time. I heard you say several times that it was what you thought I said in previous discussions we had together. I didn't raise it at the time, but what I meant is that I **suppose** the variance of the sample rate can be ignored compared to its bias. But I actually don't know for sure.  

After reading the end of your message, I just realized you actually raised the question:  
> **Sample rate stability and relevant questions**  
> Are we assuming that the sample rate is stable enough that we can apply the same to all sessions once we estimate it, or do we need to refresh the estimate regularly? How regularly? How long can the session be before our sample rate estimates becomes too erroneous? How can we measure/track this? How do we associate a sample rate to its session?

Indeed, it would be interesting to figure it out! But this is now a separate concern, since we have the above method to timestamp data.  
I still have in my ToDo (not on top of the list, I admit) the experiment you asked me to conduct to assess the sample rate bias and variance. I will make sets of recordings for different durations (like, 1 set of 10-sec recordings, 1 set of 1 min, 10 min, 1 hr, 10 hrs, etc.). This should give us a good overview of the type of bias and variance we are dealing with.

**Comment by charlie-dufort** [comment]
**On long versus short names**
When it comes to math, and especially when using concepts for which there is a widely agreed-upon notation (t, μ, σ), I by far prefer short names! Much more readable as far as I'm concerned.

**Comment by charlie-dufort** [comment]
**Less serious note on ChatGPT**
Like everyone I am so amazed by its capabilities, but it can be cruelly wrong when it misses the context. Look at this screenshot where I say "I went to the supermarket today", which I guess puts it in the casual, everyday-life context. It fell into this well-known math trap:
![File](https://user-images.githubusercontent.com/26689878/217143798-326c147b-09e6-45fb-9c8c-364dffa1612d.jpg)

Then, in another prompt, I just changed "I went to the supermarket today" for "I was at the supermarket". Removing "today" seems to be more neutral and make it switch to this "ok, this a math problem" scenario when I ask the question.  

BUT, and this is where it gets worse, if it tells you right and then you say "No, you're wrong, here's the correct answer", it will apologize and won't help you see where your mistake is! (Doesn't work for absolute truths like 1+1 = 2, tough. I tried to insist on the fact that 1+1 = 3, but it wouldn't concede 😄)
![File (2)](https://user-images.githubusercontent.com/26689878/217143806-95ffdf31-ecd2-4218-98f7-8e89e7d027e5.jpg)

**Comment by thorwhalen** [comment]
@charlie-dufort, have a look at [creek design notes wiki](https://github.com/i2mint/creek/wiki/Creek:-Design-notes), following (and probably focusing on) the link to [Slicing indexed segment streams](https://github.com/i2mint/creek/issues/2) issue that drills in to the indexing functionality, which is the direct functional layer on top of the time-stamping concern. 

If you have anything to comment on that, do it in that Slicing indexed segment streams](https://github.com/i2mint/creek/issues/2) issue.

**Comment by thorwhalen** [comment]
Would [word-clock](https://en.wikipedia.org/wiki/Word_clock) be relevant? (Found mentioned when looking up [drift-correct](https://apple.stackexchange.com/questions/59390/what-is-sound-drift-correction-on-os-x-and-how-should-i-use-it) for mac.)

**Comment by charlie-dufort** [comment]
As far as I understand, the word clock is used to have several devices play a given signal simultaneously, with no drift from one another.  It's some kind of "one-to-many" configuration: a master device provides the signal and the word clock, the slave devices play this signal using the word clock. The word clock addresses play-sync issues, but does not address timestamping issues (because it does not need to).  
Here, I would say we are dealing with the inverse, "many-to-one" configuration. We have different data sources (e.g. data acquisition terminal, PLC, etc.) and we want data to be synched and timestamped using a unique time reference: that of the oedge (OtoSense edge) host system, itself being potentially synched with NTP or some other master system.

This issue has been addressed in [this Miro board](https://miro.com/app/board/uXjVPsuJtdM=/?share_link_id=641510566530). VF, AP and myself have agreed on all the details of the timestamping principles. I know you've been remotely following the discussion, so I guess the solution sounds good enough to you too. :)  

I'll close the issue with this comment. Feel free to reopen it if you think we are missing something.
